export class MimeType {
    APPLICATION_ATOM_XML_VALUE: string = "application/atom+xml";
    APPLICATION_FORM_URLENCODED_VALUE: string = "application/x-www-form-urlencoded";
    APPLICATION_JSON_VALUE: string = "application/json";
    APPLICATION_JSON_UTF8_VALUE: string = "application/json;charset=UTF-8";
    APPLICATION_OCTET_STREAM_VALUE: string = "application/octet-stream";
    APPLICATION_PDF_VALUE: string = "application/pdf";
    APPLICATION_PROBLEM_JSON_VALUE: string = "application/problem+json";
    APPLICATION_PROBLEM_JSON_UTF8_VALUE: string = "application/problem+json;charset=UTF-8";
    APPLICATION_PROBLEM_XML_VALUE: string = "application/problem+xml";
    APPLICATION_RSS_XML_VALUE: string = "application/rss+xml";
    APPLICATION_STREAM_JSON_VALUE: string = "application/stream+json";
    APPLICATION_XHTML_XML_VALUE: string = "application/xhtml+xml";
    APPLICATION_XML_VALUE: string = "application/xml";
    IMAGE_GIF_VALUE: string = "image/gif";
    IMAGE_JPEG_VALUE: string = "image/jpeg";
    IMAGE_PNG_VALUE: string = "image/png";
    MULTIPART_FORM_DATA_VALUE: string = "multipart/form-data";
    TEXT_EVENT_STREAM_VALUE: string = "text/event-stream";
    TEXT_HTML_VALUE: string = "text/html";
    TEXT_MARKDOWN_VALUE: string = "text/markdown";
    TEXT_PLAIN_VALUE: string = "text/plain";
    TEXT_XML_VALUE: string = "text/xml";
}
